#!/usr/bin/env bash

set -e
export MIST_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

runner="local"
envoirment="dev"

cmd=$1
shift

while [[ $# > 1 ]]
do
  key="$1"

  case ${key} in
    --namespace)
      namespace="$2"
      shift
      ;;
    
    --envoirment)
      envoirment="$2"
      shift
      ;;
  esac

shift
done

if [ "${cmd}" == 'start' ]
then
  hash=$(echo -n ${namespace} | md5sum | awk '{print $1}') 
  #hash=${namespace}
  export MIST_MASTER_IP=`ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
  python ${MIST_HOME}/scripts/create-singularity-json.py ${hash} ${envoirment}
  ~/.local/bin/nd-singularity -s singularity-21.jiwiredev.com deploy -f ${MIST_HOME}/configs/mist-worker-${envoirment}-${hash}.json -r --retry=99
elif [ "${cmd}" == 'stop' ]
then
  echo "stop"
  hash=$(echo -n ${namespace} | md5sum | awk '{print $1}') 
  #hash=${namespace}
  curl -X DELETE singularity-21.jiwiredev.com/singularity/api/requests/request/mist-worker-${envoirment}-${hash}
fi
